service: user-management-api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  credentials:
    accessKeyId: xxxxxxxxxxxxxxx
    secretAccessKey: xxxxxxxxxxxxxxxx
  environment:
    poolId: "xxxxxxxxxxx"
    clientId: "xxxxxxxxxxxxxxxxxx"
    region: "us-east-1"
    accessKeyId: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    secretAccessKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

plugins:
  - serverless-plugin-browserify

package:
  individually: true
  include:
    - yarn.lock

functions:
  SignUp:
    handler: SignUp/handler.CognitoAuthMethod
    events:
      - http:
          path: SignUp
          method: post
          cors: true
  ForgetPassword:
    handler: forgotPassword/forgotPassword.ForgetPasswordMethod
    events:
      - http:
          path: ForgetPassword
          method: post
          cors: true
      - http:
          path: ResetPassword
          method: put
          cors: true
  SignIn:
    handler: signIn/handler.SignInMethod
    events:
      - http:
          path: SignIn
          method: post
          cors: true
  # UserPoolData:
  #   handler: userPoolData/handler.GetUserPoolDataMethod
  #   events:
  #     - http:
  #         path: UserPoolData
  #         method: get
  #         cors: true
  # ValidateUser:
  #   handler: validateUser/handler.ValidateUserMethod
  #   events:
  #     - http:
  #         path: ValidateUser
  #         method: post
  #         cors: true
